### ISSUE TITLE
Difficulty with Bruker FlexImaging Data Files

### ISSUE THREAD

**Issue by EmilySekera** [AlanRace/SpectralAnalysis#17]
Hello,

Adam asked me to reach out and post the issue I've been having when attempting to use your package.

I was recently attempting to utilize SpectralAnalysis for data I had obtained from an imaging run that was completed on a Bruker FT-ICR. I was able to manage to get some data loaded but unfortunately it has run across similar issues to that I had with MSiReader and have talked to Ken about. He had attempted utilizing imzML converter to remove empty scans with no luck. He also ran the data through the imzMLValidator with no errors output.

The file it loads is primarily blank black space with a small portion of the bottom right corner actually displaying my data. Due to the size of the file I assume that this is why the software has been unable to work for me and tends to freeze up. 

If you would like me to send any data files or provide any further information, please let me know.

Best,

Emily

**Comment by AlanRace** [comment]
Hi Emily,
This is due to the fact that Bruker data store 'absolute' pixel coordinates (in respect to the imagable area), rather than relative pixel coordinates. If you can send me the .imzML part I can 'fix' it for this file. 

If you have more than one file, we'll need to come up with a more general solution.

Alan

**Comment by EmilySekera** [comment]
Hi again,

Unfortunately I do have multiple files that I am working with. Is this something that you think I may be able to fix myself with a bit of guidance? I can also reach out to Bruker and see if they have any solutions as well. 

Thanks again!

Emily

**Comment by AlanRace** [comment]
Hi Emily,
Sorry for the delay - would you be able to send me a link to the data? I'll implement a fix in the parser.

Thanks,

Alan

**Comment by EmilySekera** [comment]
Hi Alan,

Thanks for getting back to me. I have included a link to one of the smaller
data files for you. I'm currently in the middle of moving but if you need
any other files please let me know and I'll get it to you as soon as
possible.

Best,

Emily
 7dpi-section4.ibd
<https://drive.google.com/file/d/1WmcF4KlTgtvGuiBITt687851Q_VOF8g-/view?usp=drive_web>
 7dpi-section4.imzML
<https://drive.google.com/file/d/1Wix50xEUyP9N8MRx1kqopluntpnNWpVW/view?usp=drive_web>

**Comment by AlanRace** [comment]
Hi Emily,
I have now modified the underlying imzML parser to recognise when Bruker data is being read in and to automatically convert this to relative coordinate (rather than absolute) so that you can now visualise the data as expected.

Are you using the source code version? If so this is available in the lastest version 14b48bd 

If not, I will make a new standalone version soon.

Thanks,

Alan

**Comment by EmilySekera** [comment]
Hi again,

I am using the source code version, I'll be sure to try it out this
morning.

Thanks again for all of your help!

Best,

Emily
